import { configDotenv } from 'dotenv';
configDotenv();

const development = {
    NODE_ENV: process.env.DEV_FOUNDRY_NODE_ENV,
    PORT: process.env.DEV_FOUNDRY_PORT,
    SALT_ROUND: process.env.DEV_FOUNDRY_SALT_ROUND,
    CRYPTO_OTP_LENGTH: process.env.DEV_FOUNDRY_CRYPTO_OTP_LENGTH,
    DATABASE_URL: process.env.DEV_FOUNDRY_DEV_DATABASE_URL,
    DATABASE_NAME: process.env.DEV_FOUNDRY_DEV_DATABASE_NAME,
    CRYPTO_SECRET: process.env.DEV_FOUNDRY_CRYPTO_SECRET,
    CRYPTO_TIME_STEP: process.env.DEV_FOUNDRY_CRYPTO_TIME_STEP,
    CRYPTO_HASH_ALGO: process.env.DEV_FOUNDRY_CRYPTO_HASH_ALGO,
    DEV_FOUNDRY_ENCRYPTIONKEY: process.env.DEV_FOUNDRY_ENCRYPTIONKEY,
    DEV_FOUNDRY_ENCRYPTIONIV: process.env.DEV_FOUNDRY_ENCRYPTIONIV,
    REDIS_PASS: process.env.DEV_FOUNDRY_DEV_REDIS_PASS,
    REDIS_HOST: process.env.DEV_FOUNDRY_DEV_REDIS_HOST,
    REDIS_PORT: process.env.DEV_FOUNDRY_DEV_REDIS_PORT,


    DEV_FOUNDRY_BREVO_KEY: process.env.DEV_FOUNDRY_DEV_BREVO_KEY,
    DEV_FOUNDRY_BREVO_HOST: process.env.DEV_FOUNDRY_DEV_BREVO_HOST,
    DEV_FOUNDRY_BREVO_PASS: process.env.DEV_FOUNDRY_DEV_BREVO_PASS,
    DEV_FOUNDRY_BREVO_PORT: process.env.DEV_FOUNDRY_DEV_BREVO_PORT,
    DEV_FOUNDRY_BREVO_USER: process.env.DEV_FOUNDRY_DEV_BREVO_USER,
}

export default development;
