import { configDotenv } from 'dotenv';
configDotenv();

const production = {
    NODE_ENV: process.env.DEV_FOUNDRY_NODE_ENV,
    PORT: process.env.DEV_FOUNDRY_PORT,
    SALT_ROUND: process.env.DEV_FOUNDRY_SALT_ROUND,
    CRYPTO_OTP_LENGTH: process.env.DEV_FOUNDRY_CRYPTO_OTP_LENGTH,
    DATABASE_URL: process.env.DEV_FOUNDRY_PROD_DATABASE_URL,
    DATABASE_NAME: process.env.DEV_FOUNDRY_PROD_DATABASE_NAME,
    CRYPTO_SECRET: process.env.DEV_FOUNDRY_PROD_CRYPTO_SECRET,
    CRYPTO_TIME_STEP: process.env.DEV_FOUNDRY_PROD_CRYPTO_TIME_STEP,
    CRYPTO_HASH_ALGO: process.env.DEV_FOUNDRY_PROD_CRYPTO_HASH_ALGO,
    DEV_FOUNDRY_ENCRYPTIONKEY: process.env.DEV_FOUNDRY_ENCRYPTIONKEY,
    DEV_FOUNDRY_ENCRYPTIONIV: process.env.DEV_FOUNDRY_ENCRYPTIONIV,


    DEV_FOUNDRY_BREVO_KEY: process.env.DEV_FOUNDRY_PROD_BREVO_KEY,
    DEV_FOUNDRY_BREVO_HOST: process.env.DEV_FOUNDRY_PROD_BREVO_HOST,
    DEV_FOUNDRY_BREVO_PASS: process.env.DEV_FOUNDRY_PROD_BREVO_PASS,
    DEV_FOUNDRY_BREVO_PORT: process.env.DEV_FOUNDRY_PROD_BREVO_PORT,
    DEV_FOUNDRY_BREVO_USER: process.env.DEV_FOUNDRY_PROD_BREVO_USER,
}

export default production;