export const OPERATION_SUCCESSFUL = (resource: string) => `${resource} operation successful.`;
export const INVALID_CREDENTIALS = (resource: string) => `Invalid ${resource} credentials.`;
export const RESOURCE_ALREADY_EXISTS = (resource: string) => `This ${resource} already exists.`;
export const PASSWORD_RESET_MAIL_SENT = (resource: string) => `A 6-digit OTP code was successfully sent to ${resource}`;
export const EXPIRED_RESOURCE = (resource: string) => `Invalid or expired ${resource}.`;
export const FETCHED_DATA_SUCCESSFULLY = (resource: string) => `Successfully fetched ${resource}.`;
export const CREATED_DATA_SUCCESSFULLY = (resource: string) => `${resource} created successfully.`;
export const DELETED_DATA_SUCCESSFULLY = (resource: string) => `${resource} successfully deleted.`;
export const RESOURCE_MESSAGE = (resource: string) => `${resource}`;
export const OPERATION_FAILED = (resource: string) => `${resource} operation failed.`;
export const UPLOADED_RESOURCE_SUCCESSFULLY = (resource: string) => `${resource} uploaded successfully.`;
export const RESOURCE_NOT_FOUND = (resource: string) => `${resource} not found.`;
export const SAME_DATA = (resource: string) => `${resource} are the same.`;
export const NO_TOKEN = 'Please provide a token';
export const ADMIN_HAS_NO_PERMISSIONS = 'User has no active permissions';
export const RESOURCE_ID_SENT_NOT_EXISTS = (resourceId: string) => `resource with resource id ${resourceId} does not exist`;
export const RESOURCE_REPEATING_IN_PAYLOAD = (resourceName: string) => `resource "${resourceName}" is repeating more than once`;
export const CANNOT_PERFORM_ACTION = (action: string, resource: string) => `User cannot perform ${action.toUpperCase()} action on ${resource} module`;
export const NO_RESOURCE_ACCESS = (resource: string) => `User does not have access to ${resource} resource.`;
export const UPDATED_DATA_SUCCESSFULLY = (resource: string) => `Successfully updated ${resource}.`;
export const RESOURCE_DOES_NOT_EXIST = (resource: string) => `This ${resource} does not exist.`;
export const ASSIGN_ADMIN = (resource: string) => `${resource} role cannot be assigned to a staff`;
