export const userLogin = () => 'Logged in successfully';
export const userLoginFailed = () => 'Login failed';
export const userSignUpRequest = () => 'Verify new account email successfully';
export const userSignUpRequestFailed = () => 'Verify new account email failed';
export const userForgotPasswordRequest = () => 'Verify account email successfully';
export const userForgotPasswordRequestFailed = () => 'Failed to verify account';
export const userResetPassword = () => 'Reset password successfully';
export const userResetPasswordFailed = () => 'Failed to reset password';
export const userVerifyOtp = () => 'Verify otp sent successfully';
export const userVerifyOtpFailed = () => 'Failed to verify otp';
export const userCreateAccount = () => 'Created stashwise account successfully';
export const userCreateAccountFailed = () => 'Failed to create account';
export const userEditDetails = (detail: string) => `Updated stashwise account "${detail}" successfully`;
export const userEditDetailsFailed = (detail: string, action: string) => `Failed to ${action} stashwise account "${detail}" successfully`;
export const userProfileDetails = (detail: string) => `Fetched stashwise account profile: "${detail}" successfully`;
export const dataNotFound = (detail: string) => `Failed to find "${detail}" in the system`;
export const userBvnLookupFailed = (detail: string) => `Failed to initiate stashwise user "${detail}" BVN Lookup.`;
export const userSingleView = (detail: string) => `Viewed "${detail}" successfully.`;
export const userDataView = (detail: string) => `Fetched and filtered "${detail}" data successfully.`;
export const dataDeleted = (detail: string) => `Deleted "${detail}" data successfully.`;
export const userSingleViewFailed = (detail: string) => `Failed to view "${detail}".`;